### ISSUE TITLE
I can't download layoffs files

### ISSUE THREAD

**Issue by Awatiffff** [AlexTheAnalyst/MySQL-YouTube-Series#9]
I've been trying to download files but it's not working please assist 
thank you in advance

**Comment by Awatiffff** [comment]
I found a way and it worked if anyone still struggling, you can simply download all the files as ZIP  :))))
good luck !

**Comment by BNinja95** [comment]
> I found a way and it worked if anyone still struggling, you can simply download all the files as ZIP :)))) good luck !

How did you download the file as ZIP? I am struggling, could not do it

**Comment by arnoldeeii-wq** [comment]
how'd you get around downloading it please?
